version: '3'
services:
  proxy:
    image: caddy:2-alpine
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - static:/static/
    ports:
      - 80:80
      - 443:443
    env_file: .env
    restart: always

  server:
    image: mensaqueuebot
    volumes:
        - db_data:${MENSA_QUEUE_BOT_DB_PATH}
        - static:/static/
    env_file: .env
    environment:
      GIN_MODE: release
    restart: always
volumes:
  caddy_data:
  db_data:
  static:
