---
- name: Mensaqueuebot database download playbook
  # Run with -K to ask for password
  hosts: SOME_TODO_IP
  tasks:
      - name: Copy DB from location within docker to main env
        become: yes
        ansible.builtin.command:
            cmd: cp /var/lib/docker/volumes/deployment_db_data/_data/queue_database.db /home/USER/databases/{{ ansible_date_time.date }}.db
      
      - name: Copy database from remote system to local
        ansible.builtin.fetch:
            src: /home/USER/databases/{{ ansible_date_time.date }}.db
            dest: ../analysis/data/
            flat: yes

